COMPILER=g++
CFLAGS=-Wall
all: qlearnrand qlearnepg qlearnrandstoch qlearnstochepg
qlearnrand: 
	$(COMPILER) $(CFLAGS) -I ./  qlearnrand.cpp -o qlearnrand
qlearnepg: 
	$(COMPILER) $(CFLAGS) -I ./  qlearnep.cpp -o qlearnepg
qlearnrandstoch: 
	$(COMPILER) $(CFLAGS) -I ./  qlearnrandstoch.cpp -o qlearnrandstoch
qlearnstochepg: 
	$(COMPILER) $(CFLAGS) -I ./  qlearnstochepg.cpp -o qlearnstochepg

